### PR TITLE
Mapbox

### PR DESCRIPTION
**Pull request by allyjay317**
[Trello](https://trello.com/c/aQjMdrEP/7-release-1-as-a-user-i-would-like-to-search-for-a-city-and-see-the-result-displayed-on-a-map) - As a user I would like to search for a city and see the result on a map.

### Map View
image

Mapbox-gl npm package implemented and added as a [component.](https://github.com/Lambda-School-Labs/cityspire-b-fe/blob/Mapbox/src/components/pages/Home/Map.js)

### Geocoding
image

mapbox-gl-geocoder npm package implemented, providing an autocompleted search bar that causes the map to jump to the location searched for

### Reverse Geocoding
image

mapbox-sdk npm package implemented, allowing quick api calls to retrieve the city, state and zip code of the location at the center of the map.

Reverse geocoding will not run until a second after movement of the map has stopped, in order to stop excessive api calls

### CODE REVIEW

**Comment by SMoore3773** [comment]
The map implementation looks good, and the code is well organized. Since this pull request added a whole feature it is rather large, but that is understandable. The commits were broken down logically and were easy to follow.

**Review by samir-hub — APPROVED** [review]
The motivation behind the PR is clear and the commits are small with clear titles. 
Your code is organized and clear. Your work is easy to follow because the files have descriptive names. 
However, the PR is not small enough to review easily. Next time, make smaller, more focused PRs.

**Review by SMoore3773 — APPROVED** [review]
The map implementation looks good, and the code is well organized. Since this pull request added a whole feature it is rather large, but that is understandable. The commits were broken down logically and were easy to follow.

**Review by songamugenzi — APPROVED** [review]
Very clean and organized code and files. Great job using reverse geocoding to retrieve the city/state/zip code data of the location at the center of the map.

**Comment by allyjay317** [comment]
[Release 1: As a user I would like to search for a city and see it displayed on a map](https://trello.com/c/c4hFAMyL/32-release-1-as-a-user-i-would-like-to-search-for-a-city-and-see-it-displayed-on-a-map)

**Pull request merged**
